# provider:
#   name: aws
#   runtime: nodejs14.x
  # region: ap-south-1
stage: ${env.STAGE}
custom:
  myStage: ${stage}
SUGAR-WEBSITE-TEST:
  component: "@sls-next/serverless-component@3.6.0"
#region: ap-south-1
  # inputs:
  #   domain: ["m.sugarcosmetics.com", "sugarcosmetics.com"]
  #   cloudfront:
  #     certificate:
  #       cloudFrontDefaultCertificate: true # specify false and one of IAM/ACM certificates, or specify true and omit IAM/ACM  
  inputs:
    build:
      env:
        SLS_STAGE: ${custom.myStage}
    #   # domain: ["dev", "sugarcosmetics.com"]

    domainRedirects:
      www.sugarcosmetics.com: https://in.sugarcosmetics.com
      sugarcosmetics.com: https://in.sugarcosmetics.com
  
    bucketRegion: ap-south-1
    bucketName: sugarwebsite-dev
  #   memory: 1024
  #   # cloudfront:
  #   #   distributionId: E3DWHYSRM7DGDU
      
